<a href="https://colab.research.google.com/github/gavrilovAlikhan/ML-Practice/blob/main/Student%20Scores/student_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
%pip install catboost lightgbm optuna

Requirement already satisfied: catboost in /usr/local/lib/python3.13/dist-packages (1.2.10)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.13/dist-packages (4.6.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (5.0.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (1.20.0)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.3.2.dev0)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.5)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)

## Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import TargetEncoder, OneHotEncoder, StandardScaler, MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.base import clone

from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_score, cross_val_predict
from sklearn.metrics import root_mean_squared_error

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor, Pool
from sklearn.linear_model import LinearRegression, Ridge, SGDRegressor

import optuna

import typing

import warnings

In [ ]:
TARGET = "exam_score"
N_SPLITS = 5
SEED = 42

non_relevant_columns = ['id', 'source']

ordinal_maps = {
    "gender" : {"male":0, "female":1, "other":2},
    "internet_access" : {"no":0, "yes":1},
    "sleep_quality" : {"poor":0, "average":1, "good":2},
    "facility_rating" : {"low":0, "medium":1, "high":2},
    "exam_difficulty" : {"easy":0, "moderate":1, "hard":2},
    "course" : {"ba":0, "b.sc":1, "diploma":2, "b.tech":3, "b.com":4, "bca":5, "bba":6},
    "study_method" : {"self-study":0, "online videos":1, "group study":2, "mixed":3, "coaching":4},
}

original_categorical_cols = ['gender', 'course', 'internet_access', 'sleep_quality', 'study_method', 'facility_rating', 'exam_difficulty']

# Data Loader

In [ ]:
def load_data(option: str="local"):
  '''
  returns train_df, test_df, df

  '''
  if option == "local":
    train_df = pd.read_csv('train.csv')
    test_df = pd.read_csv('test.csv')

  elif option == 'colab':
    from google.colab import drive
    drive.mount('/content/drive')
    train_df = pd.read_csv('/content/drive/MyDrive/Kaggle Practice/Student Scores/train.csv')
    test_df = pd.read_csv('/content/drive/MyDrive/Kaggle Practice/Student Scores/test.csv')

  train_df['source'] = 'train'
  test_df['source'] = 'test'
  df = pd.concat([train_df, test_df], ignore_index=True)

  return train_df, test_df, df

In [ ]:
df_train, _, df = load_data(option='colab')

# Data Splitter

In [ ]:
def data_spliter(df: pd.DataFrame, additional_drop_columns: list = []) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame]:
    '''
    return: X_train, y_train, submission_df

    '''
    train_dataset = df[df['source'] == 'train'].drop(columns=non_relevant_columns + additional_drop_columns)
    submission_dataset = df[df['source'] == 'test'].drop(columns=['source', TARGET] + additional_drop_columns)

    X_train = train_dataset.drop(columns=[TARGET])
    y_train = train_dataset[TARGET]

    return X_train, y_train, submission_dataset

# EDA

In [ ]:
df.isna().sum()

id                       0
age                      0
gender                   0
course                   0
study_hours              0
class_attendance         0
internet_access          0
sleep_hours              0
sleep_quality            0
study_method             0
facility_rating          0
exam_difficulty          0
exam_score          270000
source                   0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900000 entries, 0 to 899999
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                900000 non-null  int64
 1   age               900000 non-null  int64
 2   gender            900000 non-null  object
 3   course            900000 non-null  object
 4   study_hours       900000 non-null  float64
 5   class_attendance  900000 non-null  float64
 6   internet_access   900000 non-null  object
 7   sleep_hours       900000 non-null  float64
 8   sleep_quality     900000 non-null  object
 9   study_method      900000 non-null  object
 10  facility_rating   900000 non-null  object
 11  exam_difficulty   900000 non-null  object
 12  exam_score        630000 non-null  float64
 13  source            900000 non-null  object
dtypes: float64(4), int64(2), object(8)
memory usage: 96.1+ MB

In [ ]:
df.drop(columns=non_relevant_columns).describe(include='all').T

                     count unique       top    freq  ...   25%   50%   75%    max
age               900000.0    NaN       NaN     NaN  ...  19.0  21.0  23.0   24.0
gender              900000      3      male  301275  ...   NaN   NaN   NaN    NaN
course              900000      7    b.tech  187697  ...   NaN   NaN   NaN    NaN
study_hours       900000.0    NaN       NaN     NaN  ...  1.98   4.0  6.05   7.91
class_attendance  900000.0    NaN       NaN     NaN  ...  57.0  72.6  87.2   99.4
internet_access     900000      2       yes  828094  ...   NaN   NaN   NaN    NaN
sleep_hours       900000.0    NaN       NaN     NaN  ...   5.6   7.1   8.6    9.9
sleep_quality       900000      3      poor  305355  ...   NaN   NaN   NaN    NaN
study_method        900000      5  coaching  188395  ...   NaN   NaN   NaN    NaN
facility_rating     900000      3    medium  305898  ...   NaN   NaN   NaN    NaN
exam_difficulty     900000      3  moderate  505638  ...   NaN   NaN   NaN    NaN
exam_score        630000.0    NaN       NaN     NaN  ...  48.8  62.6  76.3  100.0

[12 rows x 11 columns]

In [ ]:
z.head()

   id  age  gender   course  ...  facility_rating  exam_difficulty exam_score  source
0   0   21  female     b.sc  ...              low             easy       78.3   train
1   1   18   other  diploma  ...           medium         moderate       46.7   train
2   2   20  female     b.sc  ...             high         moderate       99.0   train
3   3   19    male     b.sc  ...             high         moderate       63.9   train
4   4   23    male      bca  ...             high             easy      100.0   train

[5 rows x 14 columns]

## Correlations

In [ ]:
z = df.drop(columns=non_relevant_columns).copy()
z['internet_access'] = z['internet_access'].map({'no':0, 'yes':1})
z['sleep_quality'] = z['sleep_quality'].map({'average':1, 'poor':0, 'good':2})
z['facility_rating'] = z['facility_rating'].map({'medium':1, 'low':0, 'high':2})
z['exam_difficulty'] = z['exam_difficulty'].map({'moderate':1, 'easy':0, 'hard':2})
z = pd.get_dummies(z, columns=['study_method', 'course', 'gender'], dtype=int)

In [ ]:
z_corr = z.corr()
z_sorted_cols = z_corr['exam_score'].abs().sort_values(ascending=False).index.to_list()

z_corr_sorted = z_corr.loc[z_sorted_cols, z_sorted_cols]
mask = np.triu(np.ones_like(z_corr_sorted, dtype=bool), k=1)
z_corr_sorted[mask] = np.nan

### Correlation Plot

In [ ]:
corr_fig = px.imshow(
    z_corr_sorted,
    text_auto = ".2f",
    aspect=True,
    color_continuous_scale="RdBu_r",
    width=1200,
    height=800
)

corr_fig.show()

## Distribution of categorical columns by exam score